export const SET_OUTLET = 'SET_OUTLET'
export const CREATE_OUTLET = 'CREATE_OUTLET'
export const DESTROY_OUTLET = 'DESTROY_OUTLET'

export const SET_MAPPING = 'SET_MAPPING'
export const CREATE_MAPPING = 'CREATE_MAPPING'
export const DESTROY_MAPPING = 'DESTROY_MAPPING'

export const CREATE_HIERARCHY_NODE = 'ADD_HIERARCHY_NODE'
export const DESTROY_HIERARCHY_NODE = 'DESTROY_HIERARCHY_NODE'
export const MOVE_HIERARCHY_NODE = 'MOVE_HIERARCHY_NODE'
