ruby '2.1.4'
source 'https://rubygems.org'

gem 'pry', '~>0.10.1'          # pry repl

gem 'dotenv', '~>0.11.1'       # load ./.env into ENV

gem 'sequel', '~>4.14.0'       # ORM
gem 'pg', '~>0.17.1'           # db connector

gem 'slim', '~>2.0.3'          # templating

gem 'unicorn', '~>4.8.3'       # unicorn server

gem 'sinatra', '~>1.4.5'       # sinatra framework

gem 'sinatra-partial', '~>0.4.0'
gem 'sinatra-contrib', '~>1.4.2'
