# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 7e10b74eeaa57032df5a23fad3ce555290c46eac7f1fb61a677251f09848272b8c1fc1359d13c27fcae64ed9c89ad4bc2a593974cd6d5508e2645b257e7b0dc0

test:
  secret_key_base: da8ae0c353b9f9a9f767a4552cfc4540396a763f766b39216c263f49d6a5c81cd37499ff8911c844c663fc69dba55b51c562a49f1f68a240d3ddb3182903d02d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
